//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mduchesneau.Scheduled.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public Calendar()
        {
            this.ScheduleEvents = new HashSet<ScheduleEvent>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ScheduleEvent> ScheduleEvents { get; set; }
    }
}
