//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mduchesneau.Scheduled.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleEvent
    {
        public int ID { get; set; }
        public int CalendarID { get; set; }
        public string Title { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
    
        public virtual Calendar Calendar { get; set; }
    }
}
